name: Build and deploy when pushing to main
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set-up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: npm install
      - run: npm run build
      - name: Install dependencies
        run: npm ci
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}